// Code generated by go tool dist; DO NOT EDIT.

package buildcfg

import (
	"runtime"
)

const (
	DefaultGO386              = `sse2`
	DefaultGOAMD64            = `v1`
	DefaultGOARM              = `7`
	DefaultGOARM64            = `v8.0`
	DefaultGOMIPS             = `hardfloat`
	DefaultGOMIPS64           = `hardfloat`
	DefaultGOPPC64            = `power8`
	DefaultGORISCV64          = `rva20u64`
	defaultGOEXPERIMENT       = ``
	defaultGO_EXTLINK_ENABLED = ``
	defaultGO_LDSO            = ``
	version                   = `go1.25.0`
	defaultGOOS               = runtime.GOOS
	defaultGOARCH             = runtime.GOARCH
	DefaultGOFIPS140          = `off`
	DefaultCGO_ENABLED        = ""
)
